# Use the official Apache Airflow image
FROM apache/airflow:2.9.3

# Install necessary packages
RUN pip install requests pandas azure-storage-blob

# Copy your DAGs folder into the container
COPY dags /usr/local/airflow/dags

# Copy your plugins folder into the container (if you have plugins)
COPY plugins /usr/local/airflow/plugins

# Set the working directory
WORKDIR /usr/local/airflow
